version: 2

version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
deployment:
  staging:
    branch: master
    heroku:
      appname: nameless-island-28185